import Head from 'next/head'
import { useRouter } from 'next/router'

import { useEffect } from 'react'

export default function Home() {
  const router = useRouter()


  useEffect(() => {
    router.push("/spots/allSpots")
  }, [])

  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>HOME PAGE</h1>
    </div>
  )
}




