import Head from 'next/head'
import Image from 'next/image'

import { useRouter } from 'next/router'

import NewSpotForm from "../components/NewSpotForm"
import { addSpotHandler } from '../utils/APIfetchers'




export default function Home() {
  const router = useRouter()




  // Will call the fetcher for ADD located in utils
  const handleAdd = async (enteredData) => {
    await addSpotHandler(enteredData) 
    router.push("/spots/allSpots") //Navigate back to root
  }







  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NewSpotForm
        onAddSpot={handleAdd}
      />
    </div>
  )
}




